import type { PipelineConfig } from "@/lib/generate-pipeline";

export const DEFAULT_PIPELINE_CONFIG: PipelineConfig = {
  projectName: "my-app",
  projectType: "nodejs",
  ciProvider: "github-actions",
  nodeVersion: "20",
  packageManager: "npm",
  isMonorepo: false,
  monorepoTool: "none",
  workingDirectory: ".",
  enableDocker: false,
  dockerImageName: "",
  enableTests: true,
  enableLinting: true,
  enableBuild: true,
  deployTarget: "none",
  branches: ["main"],
  enableCaching: true,
  enableSecurityScan: false,
  enableE2ETesting: false,
  enableCodeFormatting: false,
  enableTypeChecking: false,
  enableDependencyAudit: false,
  enableContainerScan: false,
  enableSonarQube: false,
  ciSettings: {
    concurrency: 1,
    timeout: 60,
    retryOnFailure: false,
    parallelJobs: false,
  },
  environmentVariables: [],
  customScripts: {},
  notifications: {
    enabled: false,
    slack: { enabled: false },
    email: { enabled: false },
  },
  matrixBuild: {
    enabled: false,
    versions: [],
  },
  artifacts: {
    enabled: false,
    paths: [],
    retention: 30,
  },
  schedule: {
    enabled: false,
    cron: "",
    timezone: "UTC",
  },
  codeQuality: {
    enabled: false,
    coverageThreshold: 80,
    qualityGate: false,
  },
  performance: {
    enabled: false,
    loadTesting: false,
    benchmarks: false,
  },
  services: {
    enabled: false,
    database: {
      enabled: false,
      type: "postgresql",
      migrations: false,
    },
    redis: false,
    elasticsearch: false,
  },
  conditionalSteps: {
    enabled: false,
    rules: [],
  },
  environments: {
    enabled: false,
    stages: [],
  },
  deploymentStrategy: "rolling",
  customActions: [],
  optimization: {
    enabled: false,
    parallelizeTests: false,
    splitTests: false,
    cacheDependencies: true,
    useBuildKit: false,
  },
};
