import {
  IconBrandNodejs,
  IconBrandPython,
  IconBrandDocker,
  IconRocket,
  IconSparkles,
} from "@tabler/icons-react";
import type { PipelineConfig } from "@/lib/generate-pipeline";
import type { Icon } from "@tabler/icons-react";

export const presets: Record<string, Partial<PipelineConfig>> = {
  "basic-nodejs": {
    projectType: "nodejs",
    ciProvider: "github-actions",
    nodeVersion: "20",
    packageManager: "npm",
    enableTests: true,
    enableLinting: true,
    enableBuild: true,
    enableCaching: true,
    deployTarget: "none",
    ciSettings: { concurrency: 1, timeout: 60, retryOnFailure: false, parallelJobs: false },
  },
  "production-nodejs": {
    projectType: "nodejs",
    ciProvider: "github-actions",
    nodeVersion: "20",
    packageManager: "npm",
    enableTests: true,
    enableLinting: true,
    enableBuild: true,
    enableCaching: true,
    enableSecurityScan: true,
    enableDependencyAudit: true,
    enableCodeFormatting: true,
    enableTypeChecking: true,
    deployTarget: "vercel",
    ciSettings: { concurrency: 2, timeout: 60, retryOnFailure: true, parallelJobs: true },
    notifications: { enabled: true, slack: { enabled: false }, email: { enabled: false } },
  },
  "python-api": {
    projectType: "python",
    ciProvider: "github-actions",
    pythonVersion: "3.12",
    packageManager: "pip",
    enableTests: true,
    enableLinting: true,
    enableBuild: true,
    enableCaching: true,
    enableSecurityScan: true,
    enableDependencyAudit: true,
    deployTarget: "none",
    ciSettings: { concurrency: 1, timeout: 60, retryOnFailure: false, parallelJobs: false },
  },
  "docker-k8s": {
    projectType: "nodejs",
    ciProvider: "github-actions",
    nodeVersion: "20",
    packageManager: "npm",
    enableTests: true,
    enableLinting: true,
    enableBuild: true,
    enableCaching: true,
    enableDocker: true,
    enableContainerScan: true,
    deployTarget: "kubernetes",
    ciSettings: { concurrency: 2, timeout: 90, retryOnFailure: true, parallelJobs: true },
  },
  "full-featured": {
    projectType: "nodejs",
    ciProvider: "github-actions",
    nodeVersion: "20",
    packageManager: "npm",
    enableTests: true,
    enableLinting: true,
    enableBuild: true,
    enableCaching: true,
    enableSecurityScan: true,
    enableDependencyAudit: true,
    enableCodeFormatting: true,
    enableTypeChecking: true,
    enableE2ETesting: true,
    enableDocker: true,
    enableContainerScan: true,
    enableSonarQube: true,
    deployTarget: "aws",
    ciSettings: { concurrency: 3, timeout: 120, retryOnFailure: true, parallelJobs: true },
    notifications: { enabled: true, slack: { enabled: true }, email: { enabled: true } },
    matrixBuild: { enabled: true, versions: ["18", "20", "22"] },
    artifacts: { enabled: true, paths: ["dist/", "build/"], retention: 30 },
    codeQuality: { enabled: true, coverageThreshold: 80, qualityGate: true },
  },
};

export const presetLabels: Record<
  string,
  { label: string; description: string; icon: Icon }
> = {
  "basic-nodejs": {
    label: "Basic Node.js",
    description: "Simple setup with tests, linting & build",
    icon: IconBrandNodejs,
  },
  "production-nodejs": {
    label: "Production Node.js",
    description: "Full-featured with security & deployment",
    icon: IconRocket,
  },
  "python-api": {
    label: "Python API",
    description: "Python with security scanning",
    icon: IconBrandPython,
  },
  "docker-k8s": {
    label: "Docker + K8s",
    description: "Containerized with Kubernetes deployment",
    icon: IconBrandDocker,
  },
  "full-featured": {
    label: "Full Featured",
    description: "All features enabled for enterprise",
    icon: IconSparkles,
  },
};
